# Generated by Django 3.2.9 on 2021-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211110_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='exercise1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='exercise2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='exercise3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='exercise4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='exercise5',
            field=models.CharField(default='', max_length=30),
        ),
    ]
