# Generated by Django 3.2.9 on 2021-11-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211119_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='itIsFinished',
            field=models.BooleanField(default=False),
        ),
    ]
